{
  "internalError": 404,
  "message": "No se ha encontrado el usuario"
}